"use client";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import React from "react";
import "./globals.css";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "@/queries/queriesClient";
import { SessionProvider } from "next-auth/react";

const inter = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <QueryClientProvider client={queryClient}>
          <body className={inter.className}>{children}</body>
        </QueryClientProvider>
      </SessionProvider>
    </html>
  );
}
